title: 'Última práctica del curso'
description: 'JamStack, GithubPages - Pablo Arriola Pérez'
keywords: 'Implantación de Aplicaciones Web'
url: 'https://abc.github.io' 

nav: 
  Inicio: '/'
  Tag: '/tags.html'
  Línea de tiempo: '/timeline.html'
  About: '/about.html'
  Amigos: '/friendLink.html'

author: true
name: 'Pablo Arriola Pérez'
NickName: 'Pablo'
webtitle: 'The Last Dance'
bio: 'Biografía blablabla'
about: true
aboutyou: 'Esta es la última práctica del curso'
portraits: '/assets/rm.png' 

SNS: true
SNS-icon: 
  mail: ''
  weixin: '' 
  qq: ''
  github: 'https://github.com/pabloap7'
  Codepen: ''
  weibo: ''
  instagram: ''
  Twitter: ''
  Dribbble: ''
  Facebook: ''
  Google: ''
  zhihu: ''
  juejin: ''
  twitch: ''

paginate: 2
paginatepath: ['page:num']

footer:
  since: 2023

markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge
pygmentsTheme: 'default'

friends:
  jekyll: 'https://www.jekyll.com.cn/'

disqus: false
disqus_url: '' 
livere: true
livere_uid: 'MTAyMC8zNDI2OS8xMDgwNg==' 
Gitment: false
Gitment_owner: ''  
Gitment_repo: ''  
client_id: ''  
client_secret: ''  

social-share: true
social-share-items: ['qq', 'wechat', 'weibo', 'twitter', 'facebook']

baidu: true
baidu-url: ''
google: false
google-ID: ''

color: rgb(154,133,255) rgb(255,90,90) rgb(255,210,32) rgb(98,170,255)